### ISSUE TITLE
Fix searchableOptions gradle task failure

### ISSUE THREAD

**Issue by sdubov** [JetBrains/azure-tools-for-intellij#187]
We got an error when running a searchableOptions Gradle task when building a plugin:
```
Following output will be written to a log file /Users/sdubov/Projects/JetBrains/Plugins/azure-tools-for-intellij/PluginsAndFeatures/azure-toolkit-for-intellij/rider/build/idea-sandbox/system/log/frontend.log

> Task :rider:buildSearchableOptions FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rider:buildSearchableOptions'.
> Process 'command '/Users/sdubov/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbrx-8u202-osx-x64-b1483.49/jdk/Contents/Home/jre/bin/java'' finished with non-zero exit value 255
```

frontend.log
```
2019-04-21 20:04:42,934 | INFO  | RiderApplicationLoadListener   | [STDOUT] have 1 pages, target is 1, registering 2 keywords now...
2019-04-21 20:04:42,934 | INFO  | RiderApplicationLoadListener   | [STDOUT] keyword registration finished
2019-04-21 20:04:43,006 | INFO  | RiderApplicationLoadListener   | [STDOUT] Requesting backend page XamlPreviewOptionsPage
2019-04-21 20:04:43,504 | INFO  | RiderApplicationLoadListener   | [STDOUT] Got page for id XamlPreviewOptionsPage: OptionsPageInfo: `SettingsViewModel.optionsDialog.$.pages.[XamlPreviewOptionsPage].info.$`
2019-04-21 20:04:43,504 | INFO  | RiderApplicationLoadListener   | [STDOUT] have 1 pages, target is 1, registering 4 keywords now...
2019-04-21 20:04:43,504 | INFO  | RiderApplicationLoadListener   | [STDOUT] keyword registration finished
2019-04-21 20:04:52,345 | INFO  | RiderApplicationLoadListener   | [STDOUT] 16 SubscriptionManager.getSubscriptionDetails()
2019-04-21 20:04:52,345 | INFO  | RiderApplicationLoadListener   | [STDOUT] 16SubscriptionManagerPersist.updateAccountSubscriptionList()
2019-04-21 20:04:52,345 | INFO  | RiderApplicationLoadListener   | [STDOUT] SubscriptionManagerPersist.loadSubscriptions()
2019-04-21 20:04:53,448 | INFO  | RiderApplicationLoadListener   | [STDOUT] 16 SubscriptionManager.doSetSubscriptionDetails()
2019-04-21 20:04:53,448 | INFO  | RiderApplicationLoadListener   | [STDOUT] 16 SubscriptionManager.updateSidToTidMap()
2019-04-21 20:04:53,472 | WARN  | RiderApplicationLoadListener   | [STDERR] Apr 21, 2019 8:04:53 PM com.microsoft.applicationinsights.management.common.Logger info
2019-04-21 20:04:53,472 | WARN  | RiderApplicationLoadListener   | [STDERR] INFO: Getting available resources.
2019-04-21 20:04:53,472 | WARN  | RiderApplicationLoadListener   | [STDERR] URL Path: subscriptions/222e4844-5205-41c8-b0e7-d6d4eaafc757/providers/microsoft.insights/components?api-version=2014-08-01.
2019-04-21 20:04:53,473 | WARN  | RiderApplicationLoadListener   | [STDERR] Apr 21, 2019 8:04:53 PM com.microsoft.applicationinsights.management.common.Logger info
2019-04-21 20:04:53,473 | WARN  | RiderApplicationLoadListener   | [STDERR] INFO: Executing GET operation for path subscriptions/222e4844-5205-41c8-b0e7-d6d4eaafc757/providers/microsoft.insights/components?api-version=2014-08-01.
2019-04-21 20:04:53,473 | WARN  | RiderApplicationLoadListener   | [STDERR] API version: 2014-08-01.
2019-04-21 20:04:53,473 | WARN  | RiderApplicationLoadListener   | [STDERR] Apr 21, 2019 8:04:53 PM com.microsoft.applicationinsights.management.common.Logger info
2019-04-21 20:04:53,473 | WARN  | RiderApplicationLoadListener   | [STDERR] INFO: Generating SSL connection.
2019-04-21 20:04:53,473 | WARN  | RiderApplicationLoadListener   | [STDERR] Apr 21, 2019 8:04:53 PM com.microsoft.applicationinsights.management.common.Logger info
2019-04-21 20:04:53,473 | WARN  | RiderApplicationLoadListener   | [STDERR] INFO: Getting response.
2019-04-21 20:04:54,079 | WARN  | RiderApplicationLoadListener   | [STDERR] Apr 21, 2019 8:04:54 PM com.microsoft.applicationinsights.management.common.Logger info
2019-04-21 20:04:54,079 | WARN  | RiderApplicationLoadListener   | [STDERR] INFO: REST operation finished successfully. Response code: 200, Status: OK.
2019-04-21 20:04:55,770 | INFO  | RiderApplicationLoadListener   | [STDOUT] Searchable options index builder failed
2019-04-21 20:04:55,772 | WARN  | RiderApplicationLoadListener   | [STDERR] java.lang.IllegalArgumentException: Argument for @NotNull parameter 'optionsPath' of com/intellij/ide/ui/search/TraverseUIStarter.wordsToOptionDescriptors must not be null
...
2019-04-21 09:17:51,020 | WARN  | RiderApplicationLoadListener   | [STDERR] java.lang.IllegalArgumentException: Argument for @NotNull parameter 'optionsPath' of com/intellij/ide/ui/search/TraverseUIStarter.wordsToOptionDescriptors must not be null
2019-04-21 09:17:51,020 | WARN  | RiderApplicationLoadListener   | [STDERR]     at com.intellij.ide.ui.search.TraverseUIStarter.$$$reportNull$$$0(TraverseUIStarter.java)
2019-04-21 09:17:51,020 | WARN  | RiderApplicationLoadListener   | [STDERR]     at com.intellij.ide.ui.search.TraverseUIStarter.wordsToOptionDescriptors(TraverseUIStarter.java)
2019-04-21 09:17:51,020 | WARN  | RiderApplicationLoadListener   | [STDERR]     at com.intellij.ide.ui.search.TraverseUIStarter.processOptionsContainingConfigurable(TraverseUIStarter.java:224)
2019-04-21 09:17:51,020 | WARN  | RiderApplicationLoadListener   | [STDERR]     at com.intellij.ide.ui.search.TraverseUIStarter.startup(TraverseUIStarter.java:130)
2019-04-21 09:17:51,020 | WARN  | RiderApplicationLoadListener   | [STDERR]     at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:87)
2019-04-21 09:17:51,020 | WARN  | RiderApplicationLoadListener   | [STDERR]     at com.intellij.idea.IdeaApplication.lambda$run$1(IdeaApplication.java:211)
2019-04-21 09:17:51,020 | WARN  | RiderApplicationLoadListener   | [STDERR]     at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
2019-04-21 09:17:51,020 | WARN  | RiderApplicationLoadListener   | [STDERR]     at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:211)
2019-04-21 09:17:51,020 | WARN  | RiderApplicationLoadListener   | [STDERR]     at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
2019-04-21 09:17:51,020 | WARN  | RiderApplicationLoadListener   | [STDERR]     at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
2019-04-21 09:17:51,020 | WARN  | RiderApplicationLoadListener   | [STDERR]     at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
2019-04-21 09:17:51,020 | WARN  | RiderApplicationLoadListener   | [STDERR]     at java.awt.EventQueue.access$500(EventQueue.java:98)
2019-04-21 09:17:51,020 | WARN  | RiderApplicationLoadListener   | [STDERR]     at java.awt.EventQueue$3.run(EventQueue.java:715)
2019-04-21 09:17:51,020 | WARN  | RiderApplicationLoadListener   | [STDERR]     at java.awt.EventQueue$3.run(EventQueue.java:709)
2019-04-21 09:17:51,021 | WARN  | RiderApplicationLoadListener   | [STDERR]     at java.security.AccessController.doPrivileged(Native Method)
2019-04-21 09:17:51,021 | WARN  | RiderApplicationLoadListener   | [STDERR]     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
2019-04-21 09:17:51,021 | WARN  | RiderApplicationLoadListener   | [STDERR]     at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
2019-04-21 09:17:51,021 | WARN  | RiderApplicationLoadListener   | [STDERR]     at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:347)
2019-04-21 09:17:51,021 | WARN  | RiderApplicationLoadListener   | [STDERR]     at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
2019-04-21 09:17:51,021 | WARN  | RiderApplicationLoadListener   | [STDERR]     at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
2019-04-21 09:17:51,021 | WARN  | RiderApplicationLoadListener   | [STDERR]     at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
2019-04-21 09:17:51,021 | WARN  | RiderApplicationLoadListener   | [STDERR]     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
2019-04-21 09:17:51,021 | WARN  | RiderApplicationLoadListener   | [STDERR]     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
2019-04-21 09:17:51,021 | WARN  | RiderApplicationLoadListener   | [STDERR]     at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by maartenba** [comment]
This was fixed, right?

**Comment by sdubov** [comment]
We fixed this by configuring another set of AWS instances that run our builds. I would say partially yes :) I think we can close this issues for now.
