### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Function Apps

### ISSUE THREAD

**Issue by reemas15** [JetBrains/azure-tools-for-intellij#201]
IntelliJ build version: 2019.1.1 RD-191.6733.985
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.20.0.464-2019.1
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.\r\nTrace ID: 6a8894f0-4235-49de-92a0-a5b01e6d0100\r\nCorrelation ID: e335b31c-03bb-4bb2-8d87-1d3173e71aa6\r\nTimestamp: 2019-05-15 20:28:26Z","error_codes":[90002],"timestamp":"2019-05-15 20:28:26Z","trace_id":"6a8894f0-4235-49de-92a0-a5b01e6d0100","correlation_id":"e335b31c-03bb-4bb2-8d87-1d3173e71aa6"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.list(WebAppsInner.java:1703)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.list(TopLevelModifiableResourcesImpl.java:118)

**Comment by sdubov** [comment]
@reemas15, could you please check you use a valid Azure subscription? The exception says `Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant.`

Could you please provide some steps - when do you see this error? We might want to add a handler for this case.

**Comment by reemas15** [comment]
after uninstalling and reinstalling it seems to be working now.. but 100% the credentials were right and I have an active subscription. I cant reproduce it now.

**Comment by maartenba** [comment]
OK closing for now, feel free to reopen if the need arises
