### ISSUE TITLE
Azure Functions - Can't check/download core tools when last release is not a full release

### ISSUE THREAD

**Issue by maartenba** [JetBrains/azure-tools-for-intellij#207]
Azure Functions - Can't check/download core tools when last release is not a full release

See https://github.com/Azure/azure-functions-core-tools/releases

![image](https://user-images.githubusercontent.com/485230/58940434-bc36a080-8779-11e9-9442-5fc4a91af8a5.png)

Exception:
```
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at org.jetbrains.plugins.azure.functions.coreTools.FunctionsCoreToolsManager.determineLatestRemote(FunctionsCoreToolsManager.kt:270)
	at org.jetbrains.plugins.azure.functions.AzureCoreToolsNotification$runActivity$1.invoke(AzureCoreToolsNotification.kt:52)
	at org.jetbrains.plugins.azure.functions.AzureCoreToolsNotification$runActivity$1.invoke(AzureCoreToolsNotification.kt:40)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseOnce$1.invoke(SourceEx.kt:15)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseOnce$1.invoke(SourceEx.kt)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1$1.invoke(SourceEx.kt:26)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1$1.invoke(SourceEx.kt)
	at com.jetbrains.rd.util.reactive.IOptPropertyView$DefaultImpls.advise(Interfaces.kt:118)
	at com.jetbrains.rd.util.reactive.IOptProperty$DefaultImpls.advise(Interfaces.kt)
	at com.jetbrains.rd.util.reactive.OptProperty.advise(Property.kt:20)
	at com.jetbrains.rd.framework.impl.RdPropertyBase.advise(RdProperty.kt:84)
	at com.jetbrains.rd.framework.impl.RdOptionalProperty.advise(RdProperty.kt:141)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1.invoke(SourceEx.kt:25)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1.invoke(SourceEx.kt)
	at com.jetbrains.rd.util.lifetime.Lifetime$Companion$define$1.invoke(RLifetime.kt:40)
	at com.jetbrains.rd.util.lifetime.Lifetime$Companion$define$1.invoke(RLifetime.kt:21)
	at com.jetbrains.rd.util.lifetime.Lifetime$createNested$$inlined$also$lambda$1.invoke(RLifetime.kt:54)
	at com.jetbrains.rd.util.lifetime.Lifetime$createNested$$inlined$also$lambda$1.invoke(RLifetime.kt:20)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.executeIfAlive(RLifetime.kt:390)
	at com.jetbrains.rd.util.lifetime.Lifetime.createNested(RLifetime.kt:54)
	at com.jetbrains.rd.util.lifetime.Lifetime$Companion.define(RLifetime.kt:40)
	at com.jetbrains.rd.util.reactive.SourceExKt.adviseUntil(SourceEx.kt:24)
	at com.jetbrains.rd.util.reactive.SourceExKt.adviseOnce(SourceEx.kt:15)
	at org.jetbrains.plugins.azure.functions.AzureCoreToolsNotification.runActivity(AzureCoreToolsNotification.kt:46)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$logActivityDuration$2(StartupManagerImpl.java:152)
	at com.intellij.util.TimeoutUtil.measureExecutionTime(TimeoutUtil.java:74)
	at com.intellij.ide.startup.impl.StartupManagerImpl.logActivityDuration(StartupManagerImpl.java:152)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivitiesFromExtensions$1(StartupManagerImpl.java:140)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:360)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$queueSmartModeActivity$3(StartupManagerImpl.java:166)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:380)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:372)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Will need a bugfix release for `191`.

**Comment by maartenba** [comment]
PR merged
