### ISSUE TITLE
[Rider][ReportedByUser] Azure Services Explorer - Error Refresh resource manage module

### ISSUE THREAD

**Issue by elliereid** [JetBrains/azure-tools-for-intellij#269]
IntelliJ build version: 2019.2.3 RD-192.7317.11
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.26.0.565-2019.2
Error message: 
```
com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
	at com.microsoft.azuretools.authmanage.SubscriptionManager.doSetSubscriptionDetails(SubscriptionManager.java:122)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscriptionDetailsIfNull(SubscriptionManager.java:92)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:76)
	at com.microsoft.azuretools.utils.AzureModelController.updateSubscriptionMaps(AzureModelController.java:270)
	at com.microsoft.azuretools.core.mvp.model.AzureMvpModel.getResourceGroups(AzureMvpModel.java:130)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.arm.ResourceManagementModulePresenter.onModuleRefresh(ResourceManagementModulePresenter.java:47)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.arm.ResourceManagementModule.refreshItems(ResourceManagementModule.java:58)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:95)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:161)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgre

**Comment by sdubov** [comment]
@elliereid, thank you for your report. I'm not able to repro it from the first glance. Could you please provide some details about the issue? Do you see this error been signed in into your account? Does it have a valid subscription? Do you see this issue constantly? Can you reproduce it when refresh  other modules, but Resource Management (since we require Subscription information for all of them)?

**Comment by sdubov** [comment]
Here is the reference issue - https://github.com/microsoft/azure-tools-for-java/issues/4051
