### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Function Apps

### ISSUE THREAD

**Issue by bjorncoltof** [JetBrains/azure-tools-for-intellij#276]
In general the listing of function apps is quite slow, once in a while I get the error below.

IntelliJ build version: 2019.3.1 RD-193.5662.14
OS: Windows 10
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.26.0.607-2019.3
Error message: 
```
java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:497)
	at com.microsoft.azure.management.resources.fluentcore.utils.PagedListConverter.loadConvertedList(PagedListConverter.java:100)
	at com.microsoft.azure.management.resources.fluentcore.utils.PagedListConverter.convert(PagedListConverter.java:66)
	at com.microsoft.azure.management.appservice.implementation.FunctionAppsImpl.wrapList(FunctionAppsImpl.java:115)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.list(TopLevelModifiableResourcesImpl.java:118)
	at com.microsoft.azuretools.core.mvp.model.functionapp.AzureFunctionAppMvpModel.getAzureFunctionAppsBySubscriptionId(AzureFunctionAppMvpModel.kt:94)
	at com.microsoft.azuretools.core.mvp.model.functionapp.AzureFunctionAppMvpModel.listFunctionAppsBySubscriptionId(AzureFunctionAppMvpModel.kt:82)
	at com.microsoft.azuretools.core.mvp.model.functionapp.AzureFunctionAppMvpModel.listAllFunctionApps(AzureFunctionAppMvpModel.kt:66)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.appservice.functionapp.AzureFunctionAppModulePresenter.onModuleRefresh(AzureFunctionAppModulePresent

**Comment by wis3guy** [comment]
I second that refreshing/loading the list of Function Apps in the Azure explorer is consistently slow. Without exception i have to wait 2-5 minutes for the operation. Admittedly we have ~100 Function Apps across 3 resource groups.

![image](https://user-images.githubusercontent.com/6885003/75041514-01902f00-54bd-11ea-8cf0-8471a2909700.png)

![image](https://user-images.githubusercontent.com/6885003/75041532-0a810080-54bd-11ea-966d-6047872f03db.png)

Perhaps, if loading the list is this hard, some caching could be added? It seems i have to repopulate the list everytime i restart Rider.

```
JetBrains Rider 2019.3.3
Build #RD-193.6494.30, built on February 20, 2020
Licensed to **********
Subscription is active until December 7, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 12
Registry: ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, show.diff.preview.as.editor.tab=true, ide.borderless.title.product=false, performance.watcher.unresponsive.interval.ms=1000, ide.tooltip.initialDelay.highlighter=0, search.everywhere.settings=true, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, ide.borderless.title.project.path=false, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.borderless.title.classpath=false, ide.require.transaction.for.model.changes=false, vcs.non.modal.commit.toggle.ui=false
Non-Bundled Plugins: PlantUML integration, com.intellij.resharper.azure, com.microsoft.vso.idea, com.samdark.intellij-visual-studio-code-dark-plus, org.intellij.plugins.markdown
```

**Comment by sdubov** [comment]
Replace the logic on refresh Function Apps node in Azure Explorer with a new Azure API that uses lightweight call to get a list of function apps.

**Comment by maartenba** [comment]
Unfortunately, we have to revert this change for now.
