### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Storage Accounts

### ISSUE THREAD

**Issue by go-aegian** [JetBrains/azure-tools-for-intellij#280]
IntelliJ build version: 2019.3.4 RD-193.6494.48
OS: Windows 10
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.26.0.607-2019.3
Error message: 
```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 140 path $.primaryKey
	at com.google.gson.Gson.fromJson(Gson.java:903)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at com.google.gson.Gson.fromJson(Gson.java:774)
	at com.microsoft.tooling.msservices.helpers.ExternalStorageHelper.getList(ExternalStorageHelper.java:43)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.storage.StorageModule.refreshItems(StorageModule.java:107)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:95)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:161)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intel

**Comment by sdubov** [comment]
@sainzg, thank you for the report. I've verified basic cases when external creating storage accounts. The object is parsed as expected. @sainzg, could you please provide some steps to reproduce this issue? (since we do not store JSON data anywhere).

**Comment by maartenba** [comment]
This looks like a transient error with accessing the API.
