### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Web Apps

### ISSUE THREAD

**Issue by sjdean** [JetBrains/azure-tools-for-intellij#281]
IntelliJ build version: 2019.3.4 RD-193.6494.48
OS: Windows 10
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.26.0.607-2019.3
Error message: 
```
com.microsoft.azure.management.appservice.DefaultErrorResponseException: Status code 400, {"error":{"code":"DisallowedOperation","message":"The current subscription type is not permitted to perform operations on any provider namespace. Please use a different subscription."}}
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.listDelegate(WebAppsInner.java:1802)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.access$000(WebAppsInner.java:59)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner$5.call(WebAppsInner.java:1789)
	at com.microsof

**Comment by sdubov** [comment]
There is a response we are getting from Azure: `The current subscription type is not permitted to perform operations on any provider namespace. Please use a different subscription.`. @sjdean could you please clarify some steps to reproduce this? So, we could handle this issue on the client side. Could you also please make sure you have access to do the same operations through Azure portal to  verify if there is a non-plugin issue?
