### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Web Apps

### ISSUE THREAD

**Issue by charconstpointer** [JetBrains/azure-tools-for-intellij#282]
IntelliJ build version: 2020.1 EAP 5 RD-201.6251.35
OS: Windows 10
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.26.0.621-2020.1
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: Null refresh token in auth result
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:497)
	at com.microsoft.azure.management.resources.fluentcore.utils.PagedListConverter.loadConvertedList(PagedListConverter.java:100)
	at com.microsoft.azure.management.resources.fluentcore.utils.PagedListConverter.convert(PagedListConverter.java:66)
	at com.microsoft.azure.management.appservice.implementation.WebAppsImpl.wrapList(WebAppsImpl.java:100)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.list(TopLevelModifiableResourcesImpl.java:118)
	at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.listWebApps(AzureWebAppMvpModel.java:565)
	at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.lambda$null$1(AzureWebAppMvpModel.java:524)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230

**Comment by sdubov** [comment]
Related issue report - https://github.com/microsoft/azure-tools-for-java/issues/3548

**Comment by andxu** [comment]
Close this issue due to duplicate error: com.microsoft.azuretools.adauth.AuthException: Null refresh token in auth result
