### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Web Apps

### ISSUE THREAD

**Issue by Krangth** [JetBrains/azure-tools-for-intellij#283]
IntelliJ build version: 2019.3.4 RD-193.6494.48
OS: Windows 10
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.26.0.607-2019.3
Error message: 
```
java.lang.RuntimeException: java.io.IOException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS7000222: The provided client secret keys are expired.\r\nTrace ID: 9b55ca53-4c86-49db-8aab-a3848f3a0500\r\nCorrelation ID: 8ade3bab-dcdb-4307-b6a6-d65e9c66156c\r\nTimestamp: 2020-03-31 07:31:31Z","error":"invalid_client"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.resources.implementation.TenantsInner.list(TenantsInner.java:77)
	at com.microsoft.azure.management.resources.implementation.TenantsImpl.list(TenantsImpl.java:36)
	at com.microsoft.azuretools.sdkmanage.ServicePrincipalAzureManager.getTenants(ServicePrincipalAzureManager.java:136)
	at com.microsoft.azuretools.sdkmanage.ServicePrincipalAzureManager.getSubscriptionsWithTenant(ServicePrincipalAzureManager.java:106)
	at com.microsoft.azuretools.authmanage.SubscriptionManagerPersist.updateAccountSubscriptionList(SubscriptionManagerPersist.java:78)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscrip

**Comment by sdubov** [comment]
@Krangth, the exception is thrown by Azure API: `AADSTS7000222: The provided client secret keys are expired.`. Please take a look on your secrets on Azure portal to make sure it is not expired.

**Comment by Krangth** [comment]
that was it
