### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Function Apps

### ISSUE THREAD

**Issue by FloodCreux** [JetBrains/azure-tools-for-intellij#306]
IntelliJ build version: 2020.1.3 RD-201.7846.1
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.35.0.651-2020.1
Error message: 
```
com.microsoft.azure.management.appservice.DefaultErrorResponseException: Status code 500, {"Code":"InternalServerError","Message":null,"Target":null,"Details":[{"Message":null},{"Code":"InternalServerError"},{"ErrorEntity":{"Code":"InternalServerError","Message":null}}],"Innererror":null}
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.getDiagnosticLogsConfigurationDelegate(WebAppsInner.java:5157)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.access$2800(WebAppsInner.java:60)
	at com.microsoft.azure.management.apps

**Comment by maartenba** [comment]
This looks like a transient error with accessing the API. @FloodCreux would you have any repro steps? Does the issue persist or was this just once?
