### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Function Apps

### ISSUE THREAD

**Issue by darioquintana** [JetBrains/azure-tools-for-intellij#360]
IntelliJ build version: 2020.2.1 RD-202.6397.268
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.40.0.879-2020.2
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: 2c513982-29e1-4a9c-904f-74a349512300\r\nCorrelation ID: 7dd839d9-c03d-4197-a86d-b586e59bc3ec\r\nTimestamp: 2020-09-04 21:03:38Z","error_codes":[90002],"timestamp":"2020-09-04 21:03:38Z","trace_id":"2c513982-29e1-4a9c-904f-74a349512300","correlation_id":"7dd839d9-c03d-4197-a86d-b586e59bc3ec","error_uri":"https://login.microsoftonline.com/error?code=90002"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.list(WebAppsInner.java:1840)
	at com.microsoft.azure.management.re

**Comment by maartenba** [comment]
Need to show better errors #438

**Comment by maartenba** [comment]
This behaviour will be improved with the 2021.1 release.
