### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Redis Caches

### ISSUE THREAD

**Issue by Andre-O** [JetBrains/azure-tools-for-intellij#365]
IntelliJ build version: 2020.2.3 RD-202.7319.2
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.40.0.879-2020.2
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: unknown_user
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.redis.implementation.RedisInner.list(RedisInner.java:955)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.list(TopLevelModifiableResourcesImpl.java:118)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.rediscache.RedisCacheModulePresenter.onModuleRefresh(RedisCacheModulePresenter.java:53)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.rediscache.RedisCacheModule.refreshItems(RedisCacheModule.java:51)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:97)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:165)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:146)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openap

**Comment by maartenba** [comment]
@Andre-O which type of credential are you using? Device flow or Azure CLI?

**Comment by Andre-O** [comment]
> @Andre-O which type of credential are you using? Device flow or Azure CLI?

Device flow

**Comment by maartenba** [comment]
https://github.com/microsoft/azure-tools-for-java/issues/1643
