### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Function Apps

### ISSUE THREAD

**Issue by lx2222** [JetBrains/azure-tools-for-intellij#400]
IntelliJ build version: 2020.1.2 RD-201.7223.10
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.35.0.651-2020.1
Error message: 
```
com.microsoft.azure.management.appservice.DefaultErrorResponseException: Status code 503, {"Code":"ServiceUnavailable","Message":"The operation timed out and could not be completed. Please retry the action or try again later.","Target":null,"Details":[{"Message":"The operation timed out and could not be completed. Please retry the action or try again later."},{"Code":"ServiceUnavailable"},{"ErrorEntity":{"ExtendedCode":"51007","MessageTemplate":"The operation timed out and could not be completed. Please retry the action or try again later.","Code":"ServiceUnavailable","Message":"The operation timed out and could not be completed. Please retry the action or try again later."}}],"Innererror":null}
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.ref

**Comment by maartenba** [comment]
Seems like a transient error

**Comment by lx2222** [comment]
> Seems like a transient error

I am having this issue for 3 days. And only functions apps cannot be fetched .

**Comment by maartenba** [comment]
Could you give this a try with a newer version of Rider? (e.g. the latest early access preview of 2020.3 - www.jetbrains.com/rider/eap, can be installed side by side)

**Comment by maartenba** [comment]
@lx2222 Are you still seeing this issue in Rider 2020.3 ?

**Comment by lingjiexu** [comment]
@maartenba I do not have a chance to upgrade Rider, but I am still having issue in 2020.1.2.
