### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Function Apps

### ISSUE THREAD

**Issue by marc-wilson** [JetBrains/azure-tools-for-intellij#403]
IntelliJ build version: 2020.2.4 RD-202.7660.16
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.40.0.912-2020.2
Error message: 
```
com.microsoft.azure.management.appservice.DefaultErrorResponseException: Status code 503, {"Code":"ServiceUnavailable","Message":"The operation timed out and could not be completed. Please retry the action or try again later.","Target":null,"Details":[{"Message":"The operation timed out and could not be completed. Please retry the action or try again later."},{"Code":"ServiceUnavailable"},{"ErrorEntity":{"ExtendedCode":"51007","MessageTemplate":"The operation timed out and could not be completed. Please retry the action or try again later.","Code":"ServiceUnavailable","Message":"The operation timed out and could not be completed. Please retry the action or try again later."}}],"Innererror":null}
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.re

**Comment by marc-wilson** [comment]
Everything else loads fine, just not functions.

**Comment by maartenba** [comment]
Looks like #400
