### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Web Apps

### ISSUE THREAD

**Issue by kcootedinh** [JetBrains/azure-tools-for-intellij#411]
IntelliJ build version: 2020.3 EAP 10 RD-203.5981.86
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.9
Plugin version: 3.40.0.971-2020.3
Error message: 
```
java.lang.RuntimeException: java.io.IOException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS700082: The refresh token has expired due to inactivity.Â The token was issued on 2020-09-08T10:23:44.7887401Z and was inactive for 90.00:00:00.\r\nTrace ID: 87ba54e2-3ae5-4638-a5b7-95ea91a15600\r\nCorrelation ID: e1447667-18ee-4643-b994-4ece70f4c28d\r\nTimestamp: 2020-12-11 02:51:31Z","error":"invalid_grant","error_uri":"https:\/\/login.microsoftonline.com\/error?code=700082"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.resources.implementation.TenantsInner.list(TenantsInner.java:77)
	at com.microsoft.azure.management.resources.implementation.TenantsImpl.list(TenantsImpl.java:36)
	at com.microsoft.azuretools.sdkmanage.AzureCliAzureManager.getSubscriptionsWithTenant(AzureCliAzureManager.java:135)
	at com.microsoft.azuretools.authmanage.SubscriptionManagerPersist.updateAccountSubscriptionList(Subscript

**Comment by sdubov** [comment]
Hi @kcootedinh. You Azure token has expired. As a workaround, please re-login to Azure account. On our side we better need to add some checks and jump to login page instead. Need to make this fix in upstream repo. Here is the related ticket - https://github.com/microsoft/azure-tools-for-java/issues/4605

**Comment by kcootedinh** [comment]
Hi @sdubov,

I apologise I should have read the error a bit closer before filing this issue. I eventually did and re-authenticated. 

Thanks for the kind response.

**Comment by sdubov** [comment]
No worries, @kcootedinh. We could make a plugin more user-friendly for this case :) and suggest a solution rather then just showing an error. That's a valid issue. Thank you for reporting this!

**Comment by maartenba** [comment]
Going to close this specific one in favour of #438 ("better error messages")
