### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Function Apps (Refreshing...) (Refreshing...)

### ISSUE THREAD

**Issue by jack0fshad0ws** [JetBrains/azure-tools-for-intellij#420]
IntelliJ build version: 2020.3 RD-203.5981.141
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.9.1
Plugin version: 3.46.0.1046-2020.3
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: unknown_user
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.list(WebAppsInner.java:1840)
	at com.microsoft.azuretools.core.mvp.model.function.AzureFunctionMvpModel.listFunctionsInSubscription(AzureFunctionMvpModel.java:212)
	at com.microsoft.azuretools.core.mvp.model.function.AzureFunctionMvpModel.lambda$null$0(AzureFunctionMvpModel.java:133)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

**Comment by maartenba** [comment]
https://github.com/microsoft/azure-tools-for-java/issues/1643
