### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Container Registries

### ISSUE THREAD

**Issue by jack0fshad0ws** [JetBrains/azure-tools-for-intellij#433]
IntelliJ build version: 2020.3.2 RD-203.6682.21
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.9.1
Plugin version: 3.46.0.1054-2020.3
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: unknown_user
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.resources.implementation.ResourceGroupsInner.list(ResourceGroupsInner.java:766)
	at com.microsoft.azure.management.resources.implementation.ResourceGroupsImpl.list(ResourceGroupsImpl.java:41)
	at com.microsoft.azure.management.containerregistry.implementation.RegistriesImpl.list(RegistriesImpl.java:55)
	at com.microsoft.azuretools.core.mvp.model.container.ContainerRegistryMvpModel.listRegistryBySubscriptionId(ContainerRegistryMvpModel.java:87)
	at com.microsoft.azuretools.core.mvp.model.container.ContainerRegistryMvpModel.listContainerRegistries(ContainerRegistryMvpModel.java:72)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.container.ContainerRegistryModulePresenter.onModuleRefresh(ContainerRegistryModulePresenter.java:38)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.container.ContainerRegistryModule.refreshItems(ContainerRegistryModule.java:48)
	at com.microsoft.tooling.msservices.serviceexplorer.Refres

**Comment by sdubov** [comment]
@jack0fshad0ws, thank you for report. Could you please check if the issue is reproduced after re-login?
Related issue in upstream repo - https://github.com/microsoft/azure-tools-for-java/issues/4615
