### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Container Registries

### ISSUE THREAD

**Issue by khaosans** [JetBrains/azure-tools-for-intellij#436]
IntelliJ build version: 2020.3 RD-203.5981.141
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.9.1
Plugin version: 3.46.0.1054-2020.3
Error message: 
```
com.microsoft.azure.CloudException: Status code 401, {"error":{"code":"InvalidAuthenticationToken","message":"The access token is invalid."}}: The access token is invalid.
	at jdk.internal.reflect.GeneratedConstructorAccessor479.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.azure.management.containerregistry.implementation.RegistriesInner.listByResourceGroupDelegate(RegistriesInner.java:1095)
	at com.microsoft.azure.management.containerregistry.implementation.RegistriesInner.access$600(RegistriesInner.java:53)
	at com.microsoft.azure.management.containerregistry.implementation.RegistriesInner$36.call(RegistriesInner.java:1082)
	at com.microsoft.azure.management.containerregistry.implementation.RegistriesInner$36.call(RegistriesInner.java:1078)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnS

**Comment by sdubov** [comment]
Hi @khaosans. It looks like a login token is not valid. Could you please try to re-login to the Azure from plugin and let me know if it helps?

**Comment by maartenba** [comment]
Need to show better errors #438

**Comment by khaosans** [comment]
Yea, it was a token issue dealing with my .azure credentials.    Removing the existing credentials and doing a simple `az login` from the command line will regenerate my credentials.  Thanks!
