### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Resource Management

### ISSUE THREAD

**Issue by MarcinZiabek** [JetBrains/azure-tools-for-intellij#462]
Following the message, I have already tried several times to sign out and sign in again. I have also restarted Rider, and even my PC. This problem repeats for several days now. Every time I get the message that my login was successful (on the MS webpage). However, Rider is still complaining that I can not be authenticated.

IntelliJ build version: 2020.3.3 RD-203.7148.23
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.9.1
Plugin version: 3.46.0.1117-2020.3
Error message: 
```
java.lang.RuntimeException: java.io.IOException: Authorization is required, please sign out and sign in again
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.singleOrDefault(BlockingObservable.java:372)
	at com.microsoft.azuretools.sdkmanage.AzureManagerBase.getSubscriptions(AzureManagerBase.java:263)
	at com.microsoft.azuretools.sdkmanage.AzureManagerBase.getSubscriptionsWithTenant(AzureManagerBase.java:136)
	at com.microsoft.azuretools.sdkmanage.AzureManagerBase.getSubscriptions(AzureManagerBase.java:124)
	at com.microsoft.azuretools.utils.AzureModelController.updateSubscriptionMaps(AzureModelController.java:255)
	at com.microsoft.azuretools.core.mvp.model.AzureMvpModel.getResourceGroups(AzureMvpModel.java:140)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.arm.ResourceManagementModulePresenter.onModuleRefresh(ResourceManagementModulePresenter.java:47)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.arm.ResourceManagementModule.refreshItems(ResourceManagementModule.java:57)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:99

**Comment by maartenba** [comment]
@MarcinZiabek Looks like this  will be solved with https://github.com/JetBrains/azure-tools-for-intellij/pull/453 (in progress)

For now, can you try using the Azure CLI authentication method in Rider?

**Comment by MarcinZiabek** [comment]
I forgot to mention that this particular functionality was working for me for months. It just suddenly stopped working. Maybe it is a regression issue introduced in one of the latest plugin updates? Anyway, I am glad that the team is aware of the problem and preparing the fix - thank you very much for all your help and support.

@maartenba I did as suggested - logged in using Azure CLI. Rider successfully detected mu subscription and everything seems to work properly now. Thank you!

**Comment by maartenba** [comment]
This behaviour will be improved with the 2021.1 release.
