### ISSUE TITLE
Web apps: Publish configuration throws exception

### ISSUE THREAD

**Issue by maartenba** [JetBrains/azure-tools-for-intellij#591]
```
java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<Error><Message>An error has occurred.</Message></Error>"; line: 1, column: 2]
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:497)
	at com.microsoft.azure.management.resources.fluentcore.utils.PagedListConverter.loadConvertedList(PagedListConverter.java:100)
	at com.microsoft.azure.management.resources.fluentcore.utils.PagedListConverter.convert(PagedListConverter.java:66)
	at com.microsoft.azure.management.appservice.implementation.WebAppsImpl.wrapList(WebAppsImpl.java:100)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.listByResourceGroup(TopLevelModifiableResourcesImpl.java:123)
	at com.microsoft.azuretools.utils.AzureModelController$4$1.call(AzureModelController.java:195)
	at com.microsoft.azuretools.utils.AzureModelController$4$1.call(AzureModelController.java:192)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$0(AzureRxTaskManager.java:30)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:78)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$1(AzureRxTaskManager.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<Error><Message>An error has occurred.</Message></Error>"; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2005)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4761)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.microsoft.rest.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:137)
	at com.microsoft.rest.ServiceResponseBuilder.buildBody(ServiceResponseBuilder.java:216)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.getConfigurationDelegate(WebAppsInner.java:6072)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.access$3700(WebAppsInner.java:60)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner$147.call(WebAppsInner.java:6059)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner$147.call(WebAppsInner.java:6055)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$0(AzureRxTaskManager.java:30)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:78)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$1(AzureRxTaskManager.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$0(AzureRxTaskManager.java:30)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:78)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$1(AzureRxTaskManager.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$0(AzureRxTaskManager.java:30)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:78)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$1(AzureRxTaskManager.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorZip$Zip.start(OperatorZip.java:202)
	at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:143)
	at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:109)
	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
	at rx.Subscriber.setProducer(Subscriber.java:209)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$0(AzureRxTaskManager.java:30)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:78)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$1(AzureRxTaskManager.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastPath(OnSubscribeFromIterable.java:173)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:86)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.setProducer(OnSubscribeFilter.java:104)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$0(AzureRxTaskManager.java:30)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:78)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$1(AzureRxTaskManager.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:45)
	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:30)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$0(AzureRxTaskManager.java:30)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:78)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$1(AzureRxTaskManager.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$0(AzureRxTaskManager.java:30)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:78)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$1(AzureRxTaskManager.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$0(AzureRxTaskManager.java:30)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:78)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$1(AzureRxTaskManager.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:477)
	... 19 more
```

**Comment by maartenba** [comment]
Error was specific to a subscription. Closing for now.
