### ISSUE TITLE
Upgrading plugin to 1.162.2 in Rider breaks Settings/Plugins dialog

### ISSUE THREAD

**Issue by kevkov** [JetBrains/azure-tools-for-intellij#714]
Dialog does not display. Logs have this

```
2023-09-11 18:48:18,928 [  52887] SEVERE - #c.i.o.o.e.ConfigurableWrapper - JetBrains Rider 2023.2.1  Build #RD-232.9559.61
2023-09-11 18:48:18,928 [  52887] SEVERE - #c.i.o.o.e.ConfigurableWrapper - JDK: 17.0.8; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-09-11 18:48:18,928 [  52887] SEVERE - #c.i.o.o.e.ConfigurableWrapper - OS: Mac OS X
2023-09-11 18:48:18,929 [  52888] SEVERE - #c.i.o.o.e.ConfigurableWrapper - Plugin to blame: Azure Toolkit for Rider version: 3.50.0.1678-2023.2
2023-09-11 18:48:18,974 [  52933] SEVERE - #c.i.i.a.ShowSettingsUtilImpl - null
java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at com.microsoft.intellij.configuration.AzureRiderSettings.getAzuriteExecutable(AzureRiderSettings.kt:140)
	at org.jetbrains.plugins.azure.storage.azurite.AzuriteConfigurationPanel$createPanel$1$1$1.invoke(AzuriteConfigurationPanel.kt:59)
	at org.jetbrains.plugins.azure.storage.azurite.AzuriteConfigurationPanel$createPanel$1$1$1.invoke(AzuriteConfigurationPanel.kt:58)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:58)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:45)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:20)
	at org.jetbrains.plugins.azure.storage.azurite.AzuriteConfigurationPanel$createPanel$1$1.invoke(AzuriteConfigurationPanel.kt:58)
	at org.jetbrains.plugins.azure.storage.azurite.AzuriteConfigurationPanel$createPanel$1$1.invoke(AzuriteConfigurationPanel.kt:57)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.indent(PanelImpl.kt:398)
```

Disabling the plugin fixes the issue.

MacOS Ventura 13.5.2

**Comment by tstephansen** [comment]
I came here to report this. You can't access the settings or plugins screen at all. A workaround to fix this on mac (until the plugin is updated) is to go to ~/Library/Application Support/JetBrains/Rider2023.2/plugins and remove the azure plugin folder.

**Comment by JakubTracz** [comment]
Same on Windows

**Comment by stephenjeffreywhite** [comment]
I am having this problem as well, same exception. I figured out the same work around as @tstephansen by deleting the azure toolkit folder at this path on my windows machine: %appdata%\JetBrains\Rider2023.2\plugins

**Comment by rafaelldi** [comment]
Hello, folks. I apologise for this. Investigating the problem.

**Comment by maartenba** [comment]
If you do want to keep the plugin, another workaround is to make sure azurite is on your PATH. E.g. `npm install -g azurite`

**Comment by kevkov** [comment]
You can also do `rider disableNonBundledPlugins` from the command line and then disable the plugin permanently from the settings dialog.

**Comment by rafaelldi** [comment]
We published a [new version](https://plugins.jetbrains.com/plugin/11220-azure-toolkit-for-rider/versions/stable/394138) `3.50.0.1679-2023.2`, the problem should be fixed
