### ISSUE TITLE
V4 Failed to proceed. Unsupported text Content-Type Type: class java.lang.Object.

### ISSUE THREAD

**Issue by andymetcalfe93** [JetBrains/azure-tools-for-intellij#858]
Hi,

I've just installed V4.

When I try to deploy to my Functions app I get the following output:

`Start Function App deployment...
Collecting XXXX project artifacts...
Using configuration: Release and platform: Any CPU
Starting deployment...
Trying to deploy artifact to XXXXXXX...
Failed to proceed. Unsupported text Content-Type Type: class java.lang.Object.
`

Extract from logs below.

Any ideas?

Cheers,
Andy

`2024-07-18 15:09:42,813 [  90395]   INFO - #c.j.r.w.WebEnvironmentService - Scheduling background processing of configuration Azure - Function App: Testing Deploy
2024-07-18 15:09:42,813 [  90395]   INFO - #c.j.r.w.WebEnvironmentService - Started background processing of configuration Azure - Function App: Testing Deploy
2024-07-18 15:09:42,813 [  90395]   INFO - #c.j.r.w.WebEnvironmentService - Finished background processing of configuration Azure - Function App: Testing Deploy
2024-07-18 15:09:42,875 [  90457]   WARN - com.microsoft.azure.toolkit.lib.common.operation.OperationContext - default to NULL OperationContext, because operation or its action operation is null:null
2024-07-18 15:09:42,876 [  90458] SEVERE - #c.i.o.progress - There is no ProgressIndicator or Job in this thread, the current job is not cancellable.
java.lang.IllegalStateException: There is no ProgressIndicator or Job in this thread, the current job is not cancellable.
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:128)
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:126)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:83)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:126)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:121)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeploymentState.createDotNetRuntimeConfig(FunctionDeploymentState.kt:118)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeploymentState.creatDotNetFunctionAppConfig(FunctionDeploymentState.kt:102)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeploymentState.executeSteps(FunctionDeploymentState.kt:52)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeploymentState.executeSteps(FunctionDeploymentState.kt:32)
	at com.microsoft.azure.toolkit.intellij.legacy.common.RiderAzureRunProfileState.execute$lambda$0(RiderAzureRunProfileState.kt:33)
	at reactor.core.publisher.MonoCallable.call(MonoCallable.java:72)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:228)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-18 15:09:42,876 [  90458] SEVERE - #c.i.o.progress - JetBrains Rider 2024.1.4  Build #RD-241.18034.76
2024-07-18 15:09:42,876 [  90458] SEVERE - #c.i.o.progress - JDK: 17.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-07-18 15:09:42,876 [  90458] SEVERE - #c.i.o.progress - OS: Windows 11
2024-07-18 15:09:42,876 [  90458] SEVERE - #c.i.o.progress - Plugin to blame: Azure Toolkit for Rider version: 4.0.0-preview.6
2024-07-18 15:09:42,877 [  90459] SEVERE - #c.i.o.progress - Last Action: EditorBackSpace
2024-07-18 15:09:43,124 [  90706]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-07-18 15:09:43,124 [  90706]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-07-18 15:09:43,133 [  90715]   INFO - #c.j.r.s.c.StyleCopSettings - WRITTEN :: ENABLED: false, EDITORCONFIG_ENABLED: false
2024-07-18 15:09:43,244 [  90826]   INFO - #c.i.a.o.PathMacrosImpl - Saved path macros: {}
2024-07-18 15:09:43,257 [  90839]   INFO - #c.i.c.ComponentStoreImpl - Saving appLocalDatabaseDriverManager took 11 ms
2024-07-18 15:09:44,860 [  92442]   WARN - com.microsoft.azure.toolkit.lib.common.operation.OperationContext - default to NULL OperationContext, because operation or its action operation is null:null
2024-07-18 15:09:48,274 [  95856]   INFO - #c.j.r.b.BuildHost - Request new build: operation=CustomTargetWithExtraProperties, selectedProjectPaths='C:/Users/andyt/source/repos/XXXXXX/XXXXXX/XXXXXX.csproj', silentMode=true, activateWindowOnStart=false, diagnosticsMode=false, withoutDependencies=false
2024-07-18 15:09:48,294 [  95876]   INFO - #c.j.r.b.BuildHost - Build session started
2024-07-18 15:09:48,334 [  95916]   INFO - #c.j.r.b.BuildSessionView - new session
2024-07-18 15:09:48,825 [  96407]   INFO - #c.j.r.b.u.LazyConsoleWrapper - Done adding events
2024-07-18 15:09:49,556 [  97138]   INFO - #c.j.r.b.u.LazyConsoleWrapper - Done adding events
2024-07-18 15:09:50,204 [  97786]   INFO - #c.j.r.b.u.LazyConsoleWrapper - Done adding events
2024-07-18 15:09:50,209 [  97791]   INFO - #c.j.r.r.c.RunnableProjectListener - Runnable projects updated (4 items). Flushing icon cache.
2024-07-18 15:09:50,209 [  97791]   INFO - #c.j.r.r.c.RunnableProjectListener - Cleaned up the cache of 2 icons.
2024-07-18 15:09:50,210 [  97792]   INFO - #c.j.r.b.BuildHost - Build finished with result: BuildResult(kind=HasWarnings, showNotification=false)
2024-07-18 15:09:50,211 [  97793]   INFO - #c.j.r.b.BuildSessionView - result: BuildResult(kind=HasWarnings, showNotification=false)
2024-07-18 15:09:50,213 [  97795]   INFO - #c.j.r.b.BuildToolWindowContext - Build result: Publish succeeded with warnings - Publish succeeded with warnings at 15:09:50 

2024-07-18 15:09:50,216 [  97798]   WARN - com.microsoft.azure.toolkit.lib.common.operation.OperationContext - default to NULL OperationContext, because operation or its action operation is null:null
2024-07-18 15:09:51,525 [  99107]   INFO - #c.i.o.p.DumbServiceImpl - enter dumb mode [XXXXXX]
2024-07-18 15:09:51,536 [  99118]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@2d363ba7 (reason: Push on VFS changes)
2024-07-18 15:09:51,542 [  99124]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@2d363ba7 (reason: Push on VFS changes)
2024-07-18 15:09:51,565 [  99147]   INFO - #c.i.o.p.DumbServiceImpl - exit dumb mode [XXXXXX]
2024-07-18 15:09:51,651 [  99233]   WARN - com.microsoft.azure.toolkit.lib.common.operation.OperationContext - default to NULL OperationContext, because operation or its action operation is null:null
2024-07-18 15:09:51,652 [  99234]   WARN - com.microsoft.azure.toolkit.lib.common.operation.OperationContext - default to NULL OperationContext, because operation or its action operation is null:null
2024-07-18 15:09:51,653 [  99235]   WARN - com.microsoft.azure.toolkit.lib.common.operation.OperationContext - default to NULL OperationContext, because operation or its action operation is null:null
2024-07-18 15:09:52,562 [ 100144]   WARN - com.azure.core.implementation.serializer.HttpResponseBodyDecoder - Failed to deserialize the error entity.
Unsupported text Content-Type Type: class java.lang.Object
2024-07-18 15:09:52,565 [ 100147] SEVERE - com.azure.resourcemanager.appservice.implementation.KuduClient - Status code 409, "Run-From-Zip is set to a remote URL using WEBSITE_RUN_FROM_PACKAGE or WEBSITE_USE_ZIP app setting. Deployment is not supported in this configuration."
2024-07-18 15:09:52,570 [ 100152]   WARN - com.microsoft.azure.toolkit.intellij.common.messager.IntellijAzureMessager - caught an error by messager
com.azure.core.exception.HttpResponseException: Status code 409, "Run-From-Zip is set to a remote URL using WEBSITE_RUN_FROM_PACKAGE or WEBSITE_USE_ZIP app setting. Deployment is not supported in this configuration."
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:330)
	at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:128)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2571)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2367)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2241)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:293)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:188)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145)
	at reactor.core.publisher.MonoCallable$MonoCallableSubscription.request(MonoCallable.java:159)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.request(Operators.java:2067)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onSubscribe(MonoFlatMap.java:291)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:117)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.onSubscribe(Operators.java:2051)
	at reactor.core.publisher.FluxCallable.subscribe(FluxCallable.java:40)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
	at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2842)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126)
	at reactor.core.publisher.MonoUsing$MonoUsingSubscriber.onNext(MonoUsing.java:232)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:129)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:194)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:446)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:500)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:768)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at com.azure.core.http.netty.implementation.AzureSdkHandler.channelRead(AzureSdkHandler.java:222)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1338)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1387)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
		at reactor.core.publisher.Mono.block(Mono.java:1728)
		at com.azure.resourcemanager.appservice.implementation.FunctionAppImpl.zipDeploy(FunctionAppImpl.java:620)
		at com.microsoft.azure.toolkit.lib.appservice.deploy.ZIPFunctionDeployHandler.deploy(ZIPFunctionDeployHandler.java:17)
		at com.microsoft.azure.toolkit.lib.appservice.deploy.IFunctionDeployHandler.deploy(IFunctionDeployHandler.java:22)
		at com.microsoft.azure.toolkit.lib.appservice.function.FunctionAppBase.deploy(FunctionAppBase.java:82)
		at com.microsoft.azure.toolkit.intellij.appservice.functionapp.DeployDotNetFunctionAppTask.doExecute(DeployDotNetFunctionAppTask.kt:35)
		at com.microsoft.azure.toolkit.intellij.appservice.functionapp.DeployDotNetFunctionAppTask.doExecute(DeployDotNetFunctionAppTask.kt:18)
		at com.microsoft.azure.toolkit.lib.common.task.AzureTask.execute(AzureTask.java:160)
		at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeploymentState.executeSteps(FunctionDeploymentState.kt:73)
		at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeploymentState.executeSteps(FunctionDeploymentState.kt:32)
		at com.microsoft.azure.toolkit.intellij.legacy.common.RiderAzureRunProfileState.execute$lambda$0(RiderAzureRunProfileState.kt:33)
		at reactor.core.publisher.MonoCallable.call(MonoCallable.java:72)
		at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:228)
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		... 1 more
Caused by: java.lang.IllegalStateException: Unsupported text Content-Type Type: class java.lang.Object
	at com.azure.core.util.serializer.JacksonAdapter.deserializeText(JacksonAdapter.java:445)
	at com.azure.core.util.serializer.JacksonAdapter.lambda$deserialize$8(JacksonAdapter.java:345)
	at com.azure.core.util.serializer.JacksonAdapter.useAccessHelper(JacksonAdapter.java:483)
	at com.azure.core.util.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:338)
	at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserialize(HttpResponseBodyDecoder.java:166)
	at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserializeBody(HttpResponseBodyDecoder.java:139)
	at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.decodeByteArray(HttpResponseBodyDecoder.java:61)
	at com.azure.core.implementation.serializer.HttpResponseDecoder$HttpDecodedResponse.getDecodedBody(HttpResponseDecoder.java:93)
	at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:129)
	... 95 more`

**Comment by rafaelldi** [comment]
Hello! Here is an exception from your logs:
```
com.azure.core.exception.HttpResponseException: Status code 409, "Run-From-Zip is set to a remote URL using WEBSITE_RUN_FROM_PACKAGE or WEBSITE_USE_ZIP app setting. Deployment is not supported in this configuration."
```
Perhaps you have an environment variable that disables zip file deployment.

**Comment by andymetcalfe93** [comment]
It looks like I have an environment var WEBSITE_RUN_FROM_PACKAGE set to a blob storage endpoint. Not sure what this does or why it would prevent zip deployment, when I have successfully used this deployment in the past

**Comment by rafaelldi** [comment]
You probably didn't have it when it worked. Here is the [documentation](https://learn.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#use-website_run_from_package--url). 
This exception isn't from the plugin but from the Azure API, so I assume that if you try to deploy using `az` cli, you'll get the same error.

**Comment by rafaelldi** [comment]
So there's probably nothing we can do. I'll close the issue, feel free to reopen it if you have any questions.

**Comment by andymetcalfe93** [comment]
Sorry for the delay, I was on holiday and now catching up. I appreciate this is not an issue with the plugin, but just to clarify the solution is to simply delete the WEBSITE_RUN_FROM_PACKAGE env var?

**Comment by rafaelldi** [comment]
Maybe, here's a quote from the [documentation](https://learn.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package):

> Sets a URL that is the remote location of the specific package file you want to run. Required for functions apps running on Linux in a Consumption plan.

If you don't use this feature, you can probably disable it.

**Comment by andymetcalfe93** [comment]
I'm not familiar with the different options about how the Function App is hosted behind the scenes - I have only ever used the zip upload from Rider and I'm not sure if this maybe uploads a package to this remote location and this is how it all works.

Our Function app is using the consumption plan on Linux however, so it sounds like it might be necessary.
